package uz.lider.client.localization

object AppStrings {
    private val uz = mapOf(
        "nav_home" to "Asosiy",
        "nav_catalog" to "Katalog",
        "nav_orders" to "Buyurtmalar",
        "nav_analytics" to "Analitika",
        "nav_profile" to "Profil",
        "dash_welcome" to "Xush kelibsiz,",
        "dash_total_purchases" to "Jami xaridlar",
        "dash_debt" to "Qarzdorlik",
        "dash_bonus" to "Bonus ballar",
        "dash_active_orders" to "Aktiv buyurtmalar",
        "dash_discount_level" to "Chegirma darajasi",
        "dash_quick_actions" to "Tezkor harakatlar",
        "dash_order" to "Buyurtma",
        "dash_promotions" to "Aksiyalar",
        "dash_payment" to "To'lov",
        "dash_latest_promotions" to "So'nggi aksiyalar",
        "dash_see_all" to "Hammasi",
        "dash_recent_orders" to "Oxirgi buyurtmalar",
        "dash_last_month" to "Oxirgi oy",
        "dash_select_dates" to "Sanani tanlang",
        "dash_date_range" to "Sana oralig'i",
        "dash_preset_today" to "Bugun",
        "dash_preset_week" to "Bu hafta",
        "dash_preset_month" to "Bu oy",
        "dash_preset_all" to "Barchasi",
        "dash_clear_dates" to "Tozalash",
        "dash_apply_dates" to "Qo'llash",
        "dash_ai_title" to "AI Tavsiya",
        "dash_ai_desc" to "Siz odatda Coca Cola olasiz. Fanta va Sprite ham tavsiya qilamiz!",
        "cat_title" to "Katalog",
        "cat_all" to "Barchasi",
        "cat_favorites" to "Sevimlilar",
        "cat_favorites_empty" to "Sevimli mahsulotlar yo'q",
        "cat_search" to "Mahsulot qidirish...",
        "cat_products" to "ta mahsulot",
        "cat_sort" to "Saralash",
        "cat_sort_default" to "Standart",
        "cat_sort_price_asc" to "Narx: arzondan qimmatlashga",
        "cat_sort_price_desc" to "Narx: qimmatdan arzonga",
        "cat_sort_rating" to "Reyting bo'yicha",
        "cat_view_grid" to "Katakcha",
        "cat_view_list" to "Ro'yxat",
        "cat_add_cart" to "Savatga",
        "cat_qty_label" to "Miqdorni kiriting",
        "cat_qty_invalid" to "Noto'g'ri miqdor yoki omborda yetarli emas",
        "cat_stock" to "Qoldi",
        "no_image" to "Rasmi yo'q",
        "com_cancel" to "Bekor qilish",
        "ord_title" to "Buyurtmalar",
        "ord_all" to "Barchasi",
        "ord_search" to "Buyurtma raqami yoki mahsulot...",
        "ord_count" to "ta buyurtma",
        "ord_empty" to "Buyurtmalar yo'q",
        "ord_status_received" to "Qabul qilindi",
        "ord_status_warehouse" to "Omborda",
        "ord_status_packing" to "Yig'ilmoqda",
        "ord_status_onway" to "Yo'lda",
        "ord_status_delivered" to "Yetkazildi",
        "ord_status_cancelled" to "Bekor qilindi",
        "ord_reorder" to "Qayta buyurtma berish",
        "ord_items" to "ta mahsulot",
        "track_title" to "Buyurtma kuzatish",
        "track_eta" to "Kutilgan vaqt",
        "track_distance" to "Qolgan masofa",
        "track_courier" to "Dostavchik ma'lumoti",
        "track_online" to "Online",
        "track_delivery_addr" to "Yetkazish manzili",
        "track_step1" to "Buyurtma qabul qilindi",
        "track_step2" to "Omborda tayyorlanmoqda",
        "track_step3" to "Yig'ildi, jo'natilmoqda",
        "track_step4" to "Yo'lda (Dostavchik yetkazmoqda)",
        "track_step5" to "Yetkazildi",
        "track_active" to "Aktiv",
        "track_cancelled_hint" to "Agent buyurtmani bekor qildi",
        "track_map_locked_title" to "Xarita hali yo'q",
        "track_map_locked_hint" to "Dostavchikka yuklangandan keyin jonli xarita ochiladi",
        "track_map_fullscreen" to "To'liq ekran",
        "track_map_minimize" to "Kichraytirish",
        "dash_live_delivery" to "Buyurtma yo'lda",
        "dash_live_orders" to "Buyurtmalar yo'lda",
        "dash_live_orders_unit" to "ta",
        "dash_live_watch" to "Kuzatish",
        "dash_live_eta" to "ETA",
        "track_stops_before" to "Sizgacha %d ta manzil",
        "track_stops_next" to "Keyingi manzil — siz",
        "track_stops_total" to "Yo'nalishda %d ta manzil",
        "track_org_stops" to "%s · %d ta manzil",
        "track_org_stops_before" to "%s · Sizgacha %d ta manzil",
        "track_org_stops_next" to "%s · Keyingi manzil — siz",
        "track_hide_stops" to "Tochkalarni o'chirish",
        "track_hide_stops_hint" to "Faqat magazingacha yo'l",
        "track_pay_photo_hint" to "Pul berganingizda pul bergan insoningizni rasmga tushirish yodingizdan chiqmasin",
        "pay_photo_alert_title" to "Muhim ogohlantirish",
        "pay_photo_alert_body" to "Pul olgan insonni rasmga tushirib, telefoningizga saqlab qo'ying. Bu xavfsizligingiz uchun muhim!",
        "an_title" to "Analitika",
        "an_week" to "hafta",
        "an_month" to "oy",
        "an_year" to "yil",
        "an_total" to "Jami xarid",
        "an_orders" to "Buyurtmalar",
        "an_avg_check" to "O'rtacha chek",
        "an_goods" to "Tovarlar",
        "an_monthly_chart" to "Oylik xaridlar",
        "an_weekly" to "Haftalik dinamika",
        "an_by_category" to "Kategoriyalar bo'yicha",
        "an_top_products" to "Top mahsulotlar",
        "an_no_data" to "Ma'lumot yo'q",
        "an_load_error" to "Server bilan bog'lanib bo'lmadi",
        "an_chart_view" to "Grafik ko'rinishi",
        "an_style_bar" to "Ustun",
        "an_style_wave" to "To'lqin",
        "an_style_circle" to "Aylana",
        "an_show_more" to "Ko'proq ko'rish",
        "an_show_less" to "Yig'ish",
        "debt_title" to "Qarzdorlik",
        "debt_current" to "Joriy qarzdorlik",
        "debt_credit_limit" to "Kredit limiti",
        "debt_used" to "ishlatildi",
        "debt_total_paid" to "Jami to'langan",
        "debt_due_date" to "To'lov muddati",
        "debt_days_left" to "kun qoldi",
        "debt_dynamics" to "Qarzdorlik dinamikasi",
        "debt_last_months" to "So'nggi 6 oy",
        "debt_pay_btn" to "To'lov qilish",
        "debt_history" to "To'lovlar tarixi",
        "debt_payment" to "To'lov",
        "debt_added" to "Qarz qo'shildi",
        "debt_empty" to "Tanlangan davrda yozuvlar yo'q",
        "promo_title" to "Aksiyalar",
        "promo_discounts" to "Chegirmalar",
        "promo_bonus" to "Bonus dastur",
        "promo_cashback" to "Cashback",
        "promo_until" to "gacha",
        "promo_use_now" to "Hozir foydalanish",
        "promo_your_points" to "Sizning bonus ballaringiz",
        "promo_spend" to "Sarflash",
        "promo_history" to "Tarix",
        "promo_programs" to "Bonus dasturlari",
        "promo_active" to "Aktiv",
        "promo_inactive" to "Nofaol",
        "promo_discount_label" to "Chegirma",
        "promo_empty" to "Hozircha aksiyalar yo'q",
        "promo_this_month" to "Bu oy cashback",
        "promo_returned" to "so'm qaytarildi",
        "promo_rules" to "Cashback qoidalari",
        "notif_title" to "Bildirishnomalar",
        "notif_unread" to "O'qilmagan",
        "notif_read" to "O'qilgan",
        "notif_mark_all" to "Hammasini o'qildi",
        "notif_mock_order_title" to "Buyurtma yo'lda",
        "notif_mock_promo_title" to "Yangi aksiya",
        "notif_mock_payment_title" to "To'lov qabul qilindi",
        "notif_mock_yesterday" to "Kecha",
        "chat_online" to "Online • Shaxsiy menejer",
        "chat_placeholder" to "Xabar yozing...",
        "chat_title" to "Xabar",
        "chat_empty" to "Xabarlar yo'q",
        "chat_error" to "Xabar yuklanmadi",
        "chat_attach_photo" to "Rasm yoki video",
        "chat_attach_doc" to "Hujjat",
        "chat_file" to "Fayl",
        "chat_delete" to "O'chirish",
        "chat_delete_confirm" to "Ushbu xabarni o'chirish?",
        "chat_delete_for_all" to "Shuningdek {name} uchun ham o'chirish",
        "chat_personal_manager" to "Shaxsiy menejer",
        "prof_title" to "Profil",
        "prof_company" to "Kompaniya",
        "prof_tin" to "STIR",
        "prof_phone" to "Telefon",
        "prof_address" to "Manzil",
        "prof_manager" to "Menejer ma'lumotlari",
        "prof_delivery" to "Dostavkachi ma'lumotlari",
        "prof_branches" to "Filiallar",
        "prof_notif_settings" to "Bildirishnomalar sozlamalari",
        "prof_app_settings" to "Ilova sozlamalari",
        "prof_help" to "Yordam",
        "prof_help_modal_msg" to "Ilova bo'yicha savollaringiz bo'lsa, texnik mutaxassis bilan bog'laning.",
        "prof_help_modal_contact" to "Telegram orqali yozish",
        "prof_logout" to "Chiqish",
        "prof_sales_manager" to "Savdo menejeri",
        "cart_title" to "Savat",
        "cart_empty" to "Savat bo'sh",
        "cart_go_catalog" to "Katalogga o'tish",
        "cart_delivery_addr" to "Yetkazish manzili",
        "cart_address_missing" to "Klient manzili kiritilmagan",
        "cart_note" to "Izoh",
        "cart_note_placeholder" to "Ixtiyoriy izoh...",
        "cart_payment_type" to "To'lov turi",
        "cart_products" to "Mahsulotlar",
        "cart_delivery" to "Yetkazib berish",
        "cart_free" to "Bepul",
        "cart_total" to "Jami",
        "cart_submit" to "Buyurtma yuborish",
        "cart_cash" to "Naqd pul",
        "cart_card" to "Plastik karta",
        "cart_transfer" to "Bank o'tkazmasi",
        "cart_credit" to "Kredit",
        "cart_no_agent" to "Agent biriktirilmagan. Administrator bilan bog'laning.",
        "cart_order_failed" to "Buyurtma yuborilmadi. Qayta urinib ko'ring.",
        "network_error" to "Internet aloqasi yo'q",
        "server_error" to "Server xatosi",
        "unauthorized" to "Sessiya tugadi. Qayta kiring",
        "save_failed" to "Buyurtma yuborilmadi. Qayta urinib ko'ring.",
        "pd_info" to "Ma'lumot",
        "pd_reviews" to "Izohlar",
        "pd_desc" to "Tavsif",
        "pd_brand" to "Brend",
        "pd_category" to "Kategoriya",
        "pd_stock" to "Qoldi",
        "pd_rating" to "Reyting",
        "pd_your_rating" to "Bahongiz",
        "pd_rate_hint" to "Yulduzchani bosing",
        "pd_in_cart" to "Savatda bor ✓",
        "pd_add_cart" to "Savatga qo'shish",
        "pd_share" to "Ulashish",
        "pd_code" to "Kod",
        "com_som" to "so'm",
        "com_thousand" to "ming",
        "com_million" to "million",
        "com_billion" to "milliard",
        "com_close" to "Yopish",
        "com_back" to "Orqaga",
        "com_order_sent" to "Buyurtma yuborildi!",
        "com_order_accepted" to "Buyurtmangiz qabul qilindi ✓",
        "com_settings" to "Sozlamalar",
        "com_theme_dark" to "Tungi rejim",
        "com_theme_light" to "Kunduzgi rejim",
        "com_theme_system" to "Tizim rejimi",
        "com_text_color" to "Matn rangi",
        "com_tone_default" to "Standart",
        "com_tone_ink" to "Tim qora",
        "com_tone_navy" to "Ko'k",
        "com_tone_teal" to "Zumrad-ko'k",
        "com_tone_violet" to "Binafsha",
        "com_tone_rose" to "Pushti",
        "com_tone_amber" to "Amber",
        "com_tone_emerald" to "Yashil",
        "com_tone_slate" to "Kulrang",
        "com_language" to "Til",
        "login_title" to "Kirish",
        "login_subtitle" to "Admin yoki agent bergan login va parol bilan kiring",
        "login_username" to "Login",
        "login_username_ph" to "Masalan: client29072",
        "login_password" to "Parol",
        "login_password_ph" to "Parolni kiriting",
        "login_button" to "Kirish",
        "login_hint" to "Login va parolni savdo menejeringiz yoki admin panel orqali oling",
        "login_invalid" to "Login yoki parol noto'g'ri",
        "login_error" to "Ulanish xatoligi. Qayta urinib ko'ring",
        "login_client_only" to "Bu ilova faqat mijozlar uchun",
        "com_loading" to "Yuklanmoqda...",
    )

    private val uz_kril = mapOf(
        "nav_home" to "Асосий",
        "nav_catalog" to "Каталог",
        "nav_orders" to "Буюртмалар",
        "nav_analytics" to "Аналитика",
        "nav_profile" to "Профил",
        "dash_welcome" to "Хуш келибсиз,",
        "dash_total_purchases" to "Жами харидлар",
        "dash_debt" to "Қарздорлик",
        "dash_bonus" to "Бонус балллар",
        "dash_active_orders" to "Актив буюртмалар",
        "dash_discount_level" to "Чегирма даражаси",
        "dash_quick_actions" to "Тезкор ҳаракатлар",
        "dash_order" to "Буюртма",
        "dash_promotions" to "Акциялар",
        "dash_payment" to "Тўлов",
        "dash_latest_promotions" to "Сўнгги акциялар",
        "dash_see_all" to "Ҳаммаси",
        "dash_recent_orders" to "Охирги буюртмалар",
        "dash_last_month" to "Охирги ой",
        "dash_select_dates" to "Санани танланг",
        "dash_date_range" to "САНА ОРАЛИҒИ",
        "dash_preset_today" to "Бугун",
        "dash_preset_week" to "Бу ҳафта",
        "dash_preset_month" to "Бу ой",
        "dash_preset_all" to "Барчаси",
        "dash_clear_dates" to "Тозалаш",
        "dash_apply_dates" to "Қўллаш",
        "dash_ai_title" to "AI Тавсия",
        "dash_ai_desc" to "Сиз одатда Coca Cola оласиз. Fanta ва Sprite ҳам тавсия қиламиз!",
        "cat_title" to "Каталог",
        "cat_all" to "Барчаси",
        "cat_favorites" to "Севимлилар",
        "cat_favorites_empty" to "Севимли маҳсулотлар йўқ",
        "cat_search" to "Маҳсулот қидириш...",
        "cat_products" to "та маҳсулот",
        "cat_sort" to "Саралаш",
        "cat_sort_default" to "Стандарт",
        "cat_sort_price_asc" to "Нарх: арзондан қимматлашга",
        "cat_sort_price_desc" to "Нарх: қимматдан арзонга",
        "cat_sort_rating" to "Рейтинг бўйича",
        "cat_view_grid" to "Катакча",
        "cat_view_list" to "Рўйхат",
        "cat_add_cart" to "Саватга",
        "cat_qty_label" to "Миқдорни киритинг",
        "cat_qty_invalid" to "Нотўғри миқдор ёки омборда етарли эмас",
        "cat_stock" to "Қолди",
        "no_image" to "Расми йўқ",
        "com_cancel" to "Бекор қилиш",
        "ord_title" to "Буюртмалар",
        "ord_all" to "Барчаси",
        "ord_search" to "Буюртма рақами ёки маҳсулот...",
        "ord_count" to "та буюртма",
        "ord_empty" to "Буюртмалар йўқ",
        "ord_status_received" to "Қабул қилинди",
        "ord_status_warehouse" to "Омборда",
        "ord_status_packing" to "Йиғилмоқда",
        "ord_status_onway" to "Йўлда",
        "ord_status_delivered" to "Етказилди",
        "ord_status_cancelled" to "Бекор қилинди",
        "ord_reorder" to "Қайта буюртма бериш",
        "ord_items" to "та маҳсулот",
        "track_title" to "Буюртма кузатиш",
        "track_eta" to "Кутилган вақт",
        "track_distance" to "Қолган масофа",
        "track_courier" to "Етказиб берувчи маълумоти",
        "track_online" to "Онлайн",
        "track_delivery_addr" to "Етказиш манзили",
        "track_step1" to "Буюртма қабул қилинди",
        "track_step2" to "Омборда тайёрланмоқда",
        "track_step3" to "Йиғилди, жўнатилмоқда",
        "track_step4" to "Йўлда (Етказиб берувчи етказмоқда)",
        "track_step5" to "Етказилди",
        "track_active" to "Актив",
        "track_cancelled_hint" to "Агент буюртмани бекор қилди",
        "track_map_locked_title" to "Харита ҳали йўқ",
        "track_map_locked_hint" to "Доставчикка юклангандан кейин жонли харита очилади",
        "track_map_fullscreen" to "Тўлиқ экран",
        "track_map_minimize" to "Кичрайтириш",
        "dash_live_delivery" to "Буюртма йўлда",
        "dash_live_orders" to "Буюртмалар йўлда",
        "dash_live_orders_unit" to "та",
        "dash_live_watch" to "Кузатиш",
        "dash_live_eta" to "ETA",
        "track_stops_before" to "Сизгача %d та манзил",
        "track_stops_next" to "Кейинги манзил — сиз",
        "track_stops_total" to "Йўналишда %d та манзил",
        "track_org_stops" to "%s · %d та манзил",
        "track_org_stops_before" to "%s · Сизгача %d та манзил",
        "track_org_stops_next" to "%s · Кейинги манзил — сиз",
        "track_hide_stops" to "Точкаларни ўчириш",
        "track_hide_stops_hint" to "Фақат магазингача йўл",
        "track_pay_photo_hint" to "Пул берганингизда пул берган инсонингизни расмга тушириш ёдингиздан чиқмасин",
        "pay_photo_alert_title" to "Муҳим огоҳлантириш",
        "pay_photo_alert_body" to "Пул олган инсонни расмга тушириб, телефонингизга сақлаб қўйинг. Бу хавфсизлигингиз учун муҳим!",
        "an_title" to "Аналитика",
        "an_week" to "ҳафта",
        "an_month" to "ой",
        "an_year" to "йил",
        "an_total" to "Жами харид",
        "an_orders" to "Буюртмалар",
        "an_avg_check" to "Ўртача чек",
        "an_goods" to "Товарлар",
        "an_monthly_chart" to "Ойлик харидлар",
        "an_weekly" to "Ҳафталик динамика",
        "an_by_category" to "Категориялар бўйича",
        "an_top_products" to "Топ маҳсулотлар",
        "an_no_data" to "Маълумот йўқ",
        "an_load_error" to "Сервер билан боғланиб бўлмади",
        "an_chart_view" to "График кўриниши",
        "an_style_bar" to "Устун",
        "an_style_wave" to "Тўлқин",
        "an_style_circle" to "Айлана",
        "an_show_more" to "Кўпроқ кўриш",
        "an_show_less" to "Йиғиш",
        "debt_title" to "Қарздорлик",
        "debt_current" to "Жорий қарздорлик",
        "debt_credit_limit" to "Кредит лимити",
        "debt_used" to "ишлатилди",
        "debt_total_paid" to "Жами тўланган",
        "debt_due_date" to "Тўлов муддати",
        "debt_days_left" to "кун қолди",
        "debt_dynamics" to "Қарздорлик динамикаси",
        "debt_last_months" to "Сўнгги 6 ой",
        "debt_pay_btn" to "Тўлов қилиш",
        "debt_history" to "Тўловлар тарихи",
        "debt_payment" to "Тўлов",
        "debt_added" to "Қарз қўшилди",
        "debt_empty" to "Танланган даврда ёзувлар йўқ",
        "promo_title" to "Акциялар",
        "promo_discounts" to "Чегирмалар",
        "promo_bonus" to "Бонус дастур",
        "promo_cashback" to "Кэшбэк",
        "promo_until" to "гача",
        "promo_use_now" to "Ҳозир фойдаланиш",
        "promo_your_points" to "Сизнинг бонус баллларингиз",
        "promo_spend" to "Сарфлаш",
        "promo_history" to "Тарих",
        "promo_programs" to "Бонус дастурлари",
        "promo_active" to "Актив",
        "promo_inactive" to "Нофаол",
        "promo_discount_label" to "Чегирма",
        "promo_empty" to "Ҳозирча акциялар йўқ",
        "promo_this_month" to "Бу ой кэшбэк",
        "promo_returned" to "сўм қайтарилди",
        "promo_rules" to "Кэшбэк қоидалари",
        "notif_title" to "Билдиришномалар",
        "notif_unread" to "Ўқилмаган",
        "notif_read" to "Ўқилган",
        "notif_mark_all" to "Ҳаммасини ўқилди",
        "notif_mock_order_title" to "Буюртма йўлда",
        "notif_mock_promo_title" to "Янги акция",
        "notif_mock_payment_title" to "Тўлов қабул қилинди",
        "notif_mock_yesterday" to "Kecha",
        "chat_online" to "Онлайн • Шахсий менежер",
        "chat_placeholder" to "Хабар ёзинг...",
        "chat_title" to "Хабар",
        "chat_empty" to "Хабарлар йўқ",
        "chat_error" to "Хабар юкланмади",
        "chat_attach_photo" to "Расм ёки видео",
        "chat_attach_doc" to "Ҳужжат",
        "chat_file" to "Файл",
        "chat_delete" to "Ўчириш",
        "chat_delete_confirm" to "Ушбу хабарни ўчириш?",
        "chat_delete_for_all" to "Шунингдек {name} учун ҳам ўчириш",
        "chat_personal_manager" to "Шахсий менежер",
        "prof_title" to "Профил",
        "prof_company" to "Компания",
        "prof_tin" to "СТИР",
        "prof_phone" to "Телефон",
        "prof_address" to "Манзил",
        "prof_manager" to "Менежер маълумотлари",
        "prof_delivery" to "Етказиб берувчи маълумотлари",
        "prof_branches" to "Филиаллар",
        "prof_notif_settings" to "Билдиришномалар созламалари",
        "prof_app_settings" to "Илова созламалари",
        "prof_help" to "Ёрдам",
        "prof_help_modal_msg" to "Илова бўйича саволларингиз бўлса, техник мутахассис билан боғланинг.",
        "prof_help_modal_contact" to "Telegram орқали ёзиш",
        "prof_logout" to "Чиқиш",
        "prof_sales_manager" to "Савдо менежери",
        "cart_title" to "Сават",
        "cart_empty" to "Сават бўш",
        "cart_go_catalog" to "Каталогга ўтиш",
        "cart_delivery_addr" to "Етказиш манзили",
        "cart_address_missing" to "Клиент манзили киритилмаган",
        "cart_note" to "Изоҳ",
        "cart_note_placeholder" to "Ихтиёрий изоҳ...",
        "cart_payment_type" to "Тўлов тури",
        "cart_products" to "Маҳсулотлар",
        "cart_delivery" to "Етказиб бериш",
        "cart_free" to "Бепул",
        "cart_total" to "Жами",
        "cart_submit" to "Буюртма юбориш",
        "cart_cash" to "Нақд пул",
        "cart_card" to "Пластик карта",
        "cart_transfer" to "Банк ўтказмаси",
        "cart_credit" to "Кредит",
        "cart_no_agent" to "Агент бириктирилмаган. Администратор билан боғланинг.",
        "cart_order_failed" to "Буюртма юборилмади. Қайта уриниб кўринг.",
        "network_error" to "Интернет алоқаси йўқ",
        "server_error" to "Сервер хатоси",
        "unauthorized" to "Сессия тугади. Қайта киринг",
        "save_failed" to "Буюртма юборилмади. Қайта уриниб кўринг.",
        "pd_info" to "Маълумот",
        "pd_reviews" to "Изоҳлар",
        "pd_desc" to "Тавсиф",
        "pd_brand" to "Бренд",
        "pd_category" to "Категория",
        "pd_stock" to "Қолди",
        "pd_rating" to "Рейтинг",
        "pd_your_rating" to "Баҳонгиз",
        "pd_rate_hint" to "Юлдузчани босинг",
        "pd_in_cart" to "Саватда бор ✓",
        "pd_add_cart" to "Саватга қўшиш",
        "pd_share" to "Улашиш",
        "pd_code" to "Код",
        "com_som" to "сўм",
        "com_thousand" to "минг",
        "com_million" to "миллион",
        "com_billion" to "миллиард",
        "com_close" to "Ёпиш",
        "com_back" to "Орқага",
        "com_order_sent" to "Буюртма юборилди!",
        "com_order_accepted" to "Буюртмангиз қабул қилинди ✓",
        "com_settings" to "Созламалар",
        "com_theme_dark" to "Тунги режим",
        "com_theme_light" to "Кундузги режим",
        "com_theme_system" to "Тизим режими",
        "com_text_color" to "Матн ранги",
        "com_tone_default" to "Стандарт",
        "com_tone_ink" to "Тим қора",
        "com_tone_navy" to "Кўк",
        "com_tone_teal" to "Зумрад-кўк",
        "com_tone_violet" to "Бинафша",
        "com_tone_rose" to "Пушти",
        "com_tone_amber" to "Амбер",
        "com_tone_emerald" to "Яшил",
        "com_tone_slate" to "Кулранг",
        "com_language" to "Тил",
        "login_title" to "Кириш",
        "login_subtitle" to "Админ ёки агент берган login ва парол билан киринг",
        "login_username" to "Login",
        "login_username_ph" to "Масalan: client29072",
        "login_password" to "Парол",
        "login_password_ph" to "Паролни киритинг",
        "login_button" to "Кириш",
        "login_hint" to "Login ва паролни савдо менеджерингиз ёки админ панел орқали олинг",
        "login_invalid" to "Login ёки парол нотo'g'ri",
        "login_error" to "Уланиш хатолigi. Қайта urinib ko'ring",
        "login_client_only" to "Бу илова фақат мижozlar uchun",
        "com_loading" to "Yuklanmoqda...",
    )

    private val ru = mapOf(
        "nav_home" to "Главная",
        "nav_catalog" to "Каталог",
        "nav_orders" to "Заказы",
        "nav_analytics" to "Аналитика",
        "nav_profile" to "Профиль",
        "dash_welcome" to "Добро пожаловать,",
        "dash_total_purchases" to "Всего покупок",
        "dash_debt" to "Задолженность",
        "dash_bonus" to "Бонусные баллы",
        "dash_active_orders" to "Активные заказы",
        "dash_discount_level" to "Уровень скидки",
        "dash_quick_actions" to "Быстрые действия",
        "dash_order" to "Заказ",
        "dash_promotions" to "Акции",
        "dash_payment" to "Оплата",
        "dash_latest_promotions" to "Последние акции",
        "dash_see_all" to "Все",
        "dash_recent_orders" to "Последние заказы",
        "dash_last_month" to "Прошлый месяц",
        "dash_select_dates" to "Выберите дату",
        "dash_date_range" to "ПЕРИОД",
        "dash_preset_today" to "Сегодня",
        "dash_preset_week" to "Эта неделя",
        "dash_preset_month" to "Этот месяц",
        "dash_preset_all" to "Все",
        "dash_clear_dates" to "Очистить",
        "dash_apply_dates" to "Применить",
        "dash_ai_title" to "AI Рекомендации",
        "dash_ai_desc" to "Вы обычно берёте Coca Cola. Рекомендуем также Fanta и Sprite!",
        "cat_title" to "Каталог",
        "cat_all" to "Все",
        "cat_favorites" to "Избранное",
        "cat_favorites_empty" to "Нет избранных товаров",
        "cat_search" to "Поиск товара...",
        "cat_products" to "товаров",
        "cat_sort" to "Сортировка",
        "cat_sort_default" to "По умолчанию",
        "cat_sort_price_asc" to "Цена: по возрастанию",
        "cat_sort_price_desc" to "Цена: по убыванию",
        "cat_sort_rating" to "По рейтингу",
        "cat_view_grid" to "Сетка",
        "cat_view_list" to "Список",
        "cat_add_cart" to "В корзину",
        "cat_qty_label" to "Введите количество",
        "cat_qty_invalid" to "Неверное количество или недостаточно на складе",
        "cat_stock" to "Остаток",
        "no_image" to "Нет фото",
        "com_cancel" to "Отмена",
        "ord_title" to "Заказы",
        "ord_all" to "Все",
        "ord_search" to "Номер заказа или товар...",
        "ord_count" to "заказов",
        "ord_empty" to "Нет заказов",
        "ord_status_received" to "Принят",
        "ord_status_warehouse" to "На складе",
        "ord_status_packing" to "Комплектуется",
        "ord_status_onway" to "В пути",
        "ord_status_delivered" to "Доставлен",
        "ord_status_cancelled" to "Отменён",
        "ord_reorder" to "Повторить заказ",
        "ord_items" to "товаров",
        "track_title" to "Отслеживание заказа",
        "track_eta" to "Ожидаемое время",
        "track_distance" to "Осталось",
        "track_courier" to "Данные доставщика",
        "track_online" to "Онлайн",
        "track_delivery_addr" to "Адрес доставки",
        "track_step1" to "Заказ принят",
        "track_step2" to "Готовится на складе",
        "track_step3" to "Собран, отправлен",
        "track_step4" to "В пути (доставщик везёт)",
        "track_step5" to "Доставлен",
        "track_active" to "Активно",
        "track_cancelled_hint" to "Агент отменил заказ",
        "track_map_locked_title" to "Карта пока недоступна",
        "track_map_locked_hint" to "Живая карта откроется после загрузки доставщику",
        "track_map_fullscreen" to "Полный экран",
        "track_map_minimize" to "Свернуть",
        "dash_live_delivery" to "Заказ в пути",
        "dash_live_orders" to "Заказы в пути",
        "dash_live_orders_unit" to "шт",
        "dash_live_watch" to "Следить",
        "dash_live_eta" to "ETA",
        "track_stops_before" to "До вас %d адресов",
        "track_stops_next" to "Следующий адрес — вы",
        "track_stops_total" to "На маршруте %d адресов",
        "track_org_stops" to "%s · %d адресов",
        "track_org_stops_before" to "%s · До вас %d адресов",
        "track_org_stops_next" to "%s · Следующий адрес — вы",
        "track_hide_stops" to "Скрыть точки",
        "track_hide_stops_hint" to "Только путь до магазина",
        "track_pay_photo_hint" to "Когда передаёте деньги, не забудьте сфотографировать человека, которому платите",
        "pay_photo_alert_title" to "Важное предупреждение",
        "pay_photo_alert_body" to "Сфотографируйте человека, который принял деньги, и сохраните фото. Это важно для вашей безопасности!",
        "an_title" to "Аналитика",
        "an_week" to "неделя",
        "an_month" to "месяц",
        "an_year" to "год",
        "an_total" to "Всего покупок",
        "an_orders" to "Заказы",
        "an_avg_check" to "Средний чек",
        "an_goods" to "Товары",
        "an_monthly_chart" to "Ежемесячные покупки",
        "an_weekly" to "Недельная динамика",
        "an_by_category" to "По категориям",
        "an_top_products" to "Топ товары",
        "an_no_data" to "Нет данных",
        "an_load_error" to "Не удалось подключиться к серверу",
        "an_chart_view" to "Вид графика",
        "an_style_bar" to "Столбцы",
        "an_style_wave" to "Волна",
        "an_style_circle" to "Круг",
        "an_show_more" to "Показать больше",
        "an_show_less" to "Свернуть",
        "debt_title" to "Задолженность",
        "debt_current" to "Текущий долг",
        "debt_credit_limit" to "Кредитный лимит",
        "debt_used" to "использовано",
        "debt_total_paid" to "Всего оплачено",
        "debt_due_date" to "Срок оплаты",
        "debt_days_left" to "дней осталось",
        "debt_dynamics" to "Динамика задолженности",
        "debt_last_months" to "Последние 6 месяцев",
        "debt_pay_btn" to "Оплатить",
        "debt_history" to "История платежей",
        "debt_payment" to "Оплата",
        "debt_added" to "Долг добавлен",
        "debt_empty" to "За выбранный период записей нет",
        "promo_title" to "Акции",
        "promo_discounts" to "Скидки",
        "promo_bonus" to "Бонусная программа",
        "promo_cashback" to "Кэшбэк",
        "promo_until" to "до",
        "promo_use_now" to "Использовать сейчас",
        "promo_your_points" to "Ваши бонусные баллы",
        "promo_spend" to "Потратить",
        "promo_history" to "История",
        "promo_programs" to "Бонусные программы",
        "promo_active" to "Активно",
        "promo_inactive" to "Неактивно",
        "promo_discount_label" to "Скидка",
        "promo_empty" to "Пока нет акций",
        "promo_this_month" to "Кэшбэк за месяц",
        "promo_returned" to "сум возвращено",
        "promo_rules" to "Правила кэшбэка",
        "notif_title" to "Уведомления",
        "notif_unread" to "Непрочитанные",
        "notif_read" to "Прочитанные",
        "notif_mark_all" to "Отметить все",
        "notif_mock_order_title" to "Заказ в пути",
        "notif_mock_promo_title" to "Новая акция",
        "notif_mock_payment_title" to "Платёж получен",
        "notif_mock_yesterday" to "Вчера",
        "chat_online" to "Онлайн • Персональный менеджер",
        "chat_placeholder" to "Напишите сообщение...",
        "chat_title" to "Сообщение",
        "chat_empty" to "Нет сообщений",
        "chat_error" to "Не удалось загрузить сообщения",
        "chat_attach_photo" to "Фото или видео",
        "chat_attach_doc" to "Документ",
        "chat_file" to "Файл",
        "chat_delete" to "Удалить",
        "chat_delete_confirm" to "Удалить это сообщение?",
        "chat_delete_for_all" to "Также удалить для {name}",
        "chat_personal_manager" to "Персональный менеджер",
        "prof_title" to "Профиль",
        "prof_company" to "Компания",
        "prof_tin" to "ИНН",
        "prof_phone" to "Телефон",
        "prof_address" to "Адрес",
        "prof_manager" to "Данные менеджера",
        "prof_delivery" to "Данные доставщика",
        "prof_branches" to "Филиалы",
        "prof_notif_settings" to "Настройки уведомлений",
        "prof_app_settings" to "Настройки приложения",
        "prof_help" to "Помощь",
        "prof_help_modal_msg" to "По вопросам приложения свяжитесь с техническим специалистом.",
        "prof_help_modal_contact" to "Написать в Telegram",
        "prof_logout" to "Выйти",
        "prof_sales_manager" to "Менеджер по продажам",
        "cart_title" to "Корзина",
        "cart_empty" to "Корзина пуста",
        "cart_go_catalog" to "Перейти в каталог",
        "cart_delivery_addr" to "Адрес доставки",
        "cart_address_missing" to "Адрес клиента не указан",
        "cart_note" to "Примечание",
        "cart_note_placeholder" to "Необязательное примечание...",
        "cart_payment_type" to "Тип оплаты",
        "cart_products" to "Товары",
        "cart_delivery" to "Доставка",
        "cart_free" to "Бесплатно",
        "cart_total" to "Итого",
        "cart_submit" to "Отправить заказ",
        "cart_cash" to "Наличные",
        "cart_card" to "Банковская карта",
        "cart_transfer" to "Банковский перевод",
        "cart_credit" to "Кредит",
        "cart_no_agent" to "Агент не назначен. Обратитесь к администратору.",
        "cart_order_failed" to "Не удалось отправить заказ. Попробуйте ещё раз.",
        "network_error" to "Нет подключения к интернету",
        "server_error" to "Ошибка сервера",
        "unauthorized" to "Сессия истекла. Войдите снова",
        "save_failed" to "Не удалось отправить заказ. Попробуйте ещё раз.",
        "pd_info" to "Информация",
        "pd_reviews" to "Отзывы",
        "pd_desc" to "Описание",
        "pd_brand" to "Бренд",
        "pd_category" to "Категория",
        "pd_stock" to "Остаток",
        "pd_rating" to "Рейтинг",
        "pd_your_rating" to "Ваша оценка",
        "pd_rate_hint" to "Нажмите на звезду",
        "pd_in_cart" to "В корзине ✓",
        "pd_add_cart" to "Добавить в корзину",
        "pd_share" to "Поделиться",
        "pd_code" to "Код",
        "com_som" to "сум",
        "com_thousand" to "тысяч",
        "com_million" to "миллион",
        "com_billion" to "миллиард",
        "com_close" to "Закрыть",
        "com_back" to "Назад",
        "com_order_sent" to "Заказ отправлен!",
        "com_order_accepted" to "Ваш заказ принят ✓",
        "com_settings" to "Настройки",
        "com_theme_dark" to "Тёмная тема",
        "com_theme_light" to "Светлая тема",
        "com_theme_system" to "Системная тема",
        "com_text_color" to "Цвет текста",
        "com_tone_default" to "Стандарт",
        "com_tone_ink" to "Глубокий чёрный",
        "com_tone_navy" to "Синий",
        "com_tone_teal" to "Бирюзовый",
        "com_tone_violet" to "Фиолетовый",
        "com_tone_rose" to "Розовый",
        "com_tone_amber" to "Янтарный",
        "com_tone_emerald" to "Зелёный",
        "com_tone_slate" to "Серый",
        "com_language" to "Язык",
        "login_title" to "Вход",
        "login_subtitle" to "Войдите с логином и паролем от администратора или агента",
        "login_username" to "Логин",
        "login_username_ph" to "Например: client29072",
        "login_password" to "Пароль",
        "login_password_ph" to "Введите пароль",
        "login_button" to "Войти",
        "login_hint" to "Логин и пароль выдаёт ваш менеджер или администратор",
        "login_invalid" to "Неверный логин или пароль",
        "login_error" to "Ошибка подключения. Попробуйте снова",
        "login_client_only" to "Это приложение только для клиентов",
        "com_loading" to "Загрузка...",
    )

    private val en = mapOf(
        "nav_home" to "Home",
        "nav_catalog" to "Catalog",
        "nav_orders" to "Orders",
        "nav_analytics" to "Analytics",
        "nav_profile" to "Profile",
        "dash_welcome" to "Welcome,",
        "dash_total_purchases" to "Total purchases",
        "dash_debt" to "Debt",
        "dash_bonus" to "Bonus points",
        "dash_active_orders" to "Active orders",
        "dash_discount_level" to "Discount level",
        "dash_quick_actions" to "Quick actions",
        "dash_order" to "Order",
        "dash_promotions" to "Promotions",
        "dash_payment" to "Payment",
        "dash_latest_promotions" to "Latest promotions",
        "dash_see_all" to "See all",
        "dash_recent_orders" to "Recent orders",
        "dash_last_month" to "Last month",
        "dash_select_dates" to "Select date",
        "dash_date_range" to "DATE RANGE",
        "dash_preset_today" to "Today",
        "dash_preset_week" to "This week",
        "dash_preset_month" to "This month",
        "dash_preset_all" to "All",
        "dash_clear_dates" to "Clear",
        "dash_apply_dates" to "Apply",
        "dash_ai_title" to "AI Recommendations",
        "dash_ai_desc" to "You usually buy Coca Cola. We also recommend Fanta and Sprite!",
        "cat_title" to "Catalog",
        "cat_all" to "All",
        "cat_favorites" to "Favorites",
        "cat_favorites_empty" to "No favorite products yet",
        "cat_search" to "Search product...",
        "cat_products" to "products",
        "cat_sort" to "Sort",
        "cat_sort_default" to "Default",
        "cat_sort_price_asc" to "Price: low to high",
        "cat_sort_price_desc" to "Price: high to low",
        "cat_sort_rating" to "By rating",
        "cat_view_grid" to "Grid",
        "cat_view_list" to "List",
        "cat_add_cart" to "Add to cart",
        "cat_qty_label" to "Enter quantity",
        "cat_qty_invalid" to "Invalid quantity or insufficient stock",
        "cat_stock" to "Stock",
        "no_image" to "No image",
        "com_cancel" to "Cancel",
        "ord_title" to "Orders",
        "ord_all" to "All",
        "ord_search" to "Order number or product...",
        "ord_count" to "orders",
        "ord_empty" to "No orders yet",
        "ord_status_received" to "Received",
        "ord_status_warehouse" to "In warehouse",
        "ord_status_packing" to "Packing",
        "ord_status_onway" to "On the way",
        "ord_status_delivered" to "Delivered",
        "ord_status_cancelled" to "Cancelled",
        "ord_reorder" to "Reorder",
        "ord_items" to "items",
        "track_title" to "Order tracking",
        "track_eta" to "Estimated time",
        "track_distance" to "Distance left",
        "track_courier" to "Delivery person info",
        "track_online" to "Online",
        "track_delivery_addr" to "Delivery address",
        "track_step1" to "Order received",
        "track_step2" to "Being prepared at warehouse",
        "track_step3" to "Packed, dispatched",
        "track_step4" to "On the way (delivery person)",
        "track_step5" to "Delivered",
        "track_active" to "Active",
        "track_cancelled_hint" to "Agent cancelled the order",
        "track_map_locked_title" to "Map not available yet",
        "track_map_locked_hint" to "Live map opens after the order is loaded to the courier",
        "track_map_fullscreen" to "Full screen",
        "track_map_minimize" to "Minimize",
        "dash_live_delivery" to "Order on the way",
        "dash_live_orders" to "Orders on the way",
        "dash_live_orders_unit" to "orders",
        "dash_live_watch" to "Track",
        "dash_live_eta" to "ETA",
        "track_stops_before" to "%d stops before you",
        "track_stops_next" to "You are next",
        "track_stops_total" to "%d stops on the route",
        "track_org_stops" to "%s · %d stops",
        "track_org_stops_before" to "%s · %d stops before you",
        "track_org_stops_next" to "%s · You are next",
        "track_hide_stops" to "Hide stop points",
        "track_hide_stops_hint" to "Route to your shop only",
        "track_pay_photo_hint" to "When you pay, don't forget to photograph the person you paid",
        "pay_photo_alert_title" to "Important warning",
        "pay_photo_alert_body" to "Photograph the person who collected the payment and save it on your phone. This is important for your safety!",
        "an_title" to "Analytics",
        "an_week" to "week",
        "an_month" to "month",
        "an_year" to "year",
        "an_total" to "Total purchases",
        "an_orders" to "Orders",
        "an_avg_check" to "Avg. check",
        "an_goods" to "Goods",
        "an_monthly_chart" to "Monthly purchases",
        "an_weekly" to "Weekly dynamics",
        "an_by_category" to "By category",
        "an_top_products" to "Top products",
        "an_no_data" to "No data",
        "an_load_error" to "Could not connect to server",
        "an_chart_view" to "Chart style",
        "an_style_bar" to "Bars",
        "an_style_wave" to "Wave",
        "an_style_circle" to "Circle",
        "an_show_more" to "Show more",
        "an_show_less" to "Show less",
        "debt_title" to "Debt",
        "debt_current" to "Current debt",
        "debt_credit_limit" to "Credit limit",
        "debt_used" to "used",
        "debt_total_paid" to "Total paid",
        "debt_due_date" to "Due date",
        "debt_days_left" to "days left",
        "debt_dynamics" to "Debt dynamics",
        "debt_last_months" to "Last 6 months",
        "debt_pay_btn" to "Pay now",
        "debt_history" to "Payment history",
        "debt_payment" to "Payment",
        "debt_added" to "Debt added",
        "debt_empty" to "No records for selected period",
        "promo_title" to "Promotions",
        "promo_discounts" to "Discounts",
        "promo_bonus" to "Bonus program",
        "promo_cashback" to "Cashback",
        "promo_until" to "until",
        "promo_use_now" to "Use now",
        "promo_your_points" to "Your bonus points",
        "promo_spend" to "Spend",
        "promo_history" to "History",
        "promo_programs" to "Bonus programs",
        "promo_active" to "Active",
        "promo_inactive" to "Inactive",
        "promo_discount_label" to "Discount",
        "promo_empty" to "No promotions yet",
        "promo_this_month" to "Cashback this month",
        "promo_returned" to "returned",
        "promo_rules" to "Cashback rules",
        "notif_title" to "Notifications",
        "notif_unread" to "Unread",
        "notif_read" to "Read",
        "notif_mark_all" to "Mark all as read",
        "notif_mock_order_title" to "Order on the way",
        "notif_mock_promo_title" to "New promo",
        "notif_mock_payment_title" to "Payment received",
        "notif_mock_yesterday" to "Yesterday",
        "chat_online" to "Online • Personal manager",
        "chat_placeholder" to "Write a message...",
        "chat_title" to "Chat",
        "chat_empty" to "No messages yet",
        "chat_error" to "Failed to load messages",
        "chat_attach_photo" to "Photo or video",
        "chat_attach_doc" to "Document",
        "chat_file" to "File",
        "chat_delete" to "Delete",
        "chat_delete_confirm" to "Delete this message?",
        "chat_delete_for_all" to "Also delete for {name}",
        "chat_personal_manager" to "Personal manager",
        "prof_title" to "Profile",
        "prof_company" to "Company",
        "prof_tin" to "TIN",
        "prof_phone" to "Phone",
        "prof_address" to "Address",
        "prof_manager" to "Manager info",
        "prof_delivery" to "Delivery person info",
        "prof_branches" to "Branches",
        "prof_notif_settings" to "Notification settings",
        "prof_app_settings" to "App settings",
        "prof_help" to "Help",
        "prof_help_modal_msg" to "For app-related questions, contact our technical specialist.",
        "prof_help_modal_contact" to "Contact via Telegram",
        "prof_logout" to "Log out",
        "prof_sales_manager" to "Sales manager",
        "cart_title" to "Cart",
        "cart_empty" to "Cart is empty",
        "cart_go_catalog" to "Go to catalog",
        "cart_delivery_addr" to "Delivery address",
        "cart_address_missing" to "Client address is not set",
        "cart_note" to "Note",
        "cart_note_placeholder" to "Optional note...",
        "cart_payment_type" to "Payment type",
        "cart_products" to "Products",
        "cart_delivery" to "Delivery",
        "cart_free" to "Free",
        "cart_total" to "Total",
        "cart_submit" to "Submit order",
        "cart_cash" to "Cash",
        "cart_card" to "Bank card",
        "cart_transfer" to "Bank transfer",
        "cart_credit" to "Credit",
        "cart_no_agent" to "No agent assigned. Contact the administrator.",
        "cart_order_failed" to "Could not submit order. Please try again.",
        "network_error" to "No internet connection",
        "server_error" to "Server error",
        "unauthorized" to "Session expired. Please sign in again",
        "save_failed" to "Could not submit order. Please try again.",
        "pd_info" to "Info",
        "pd_reviews" to "Reviews",
        "pd_desc" to "Description",
        "pd_brand" to "Brand",
        "pd_category" to "Category",
        "pd_stock" to "Stock",
        "pd_rating" to "Rating",
        "pd_your_rating" to "Your rating",
        "pd_rate_hint" to "Tap a star",
        "pd_in_cart" to "In cart ✓",
        "pd_add_cart" to "Add to cart",
        "pd_share" to "Share",
        "pd_code" to "Code",
        "com_som" to "UZS",
        "com_thousand" to "thousand",
        "com_million" to "million",
        "com_billion" to "billion",
        "com_close" to "Close",
        "com_back" to "Back",
        "com_order_sent" to "Order sent!",
        "com_order_accepted" to "Your order has been accepted ✓",
        "com_settings" to "Settings",
        "com_theme_dark" to "Dark mode",
        "com_theme_light" to "Light mode",
        "com_theme_system" to "System theme",
        "com_text_color" to "Text color",
        "com_tone_default" to "Default",
        "com_tone_ink" to "Deep black",
        "com_tone_navy" to "Navy",
        "com_tone_teal" to "Teal",
        "com_tone_violet" to "Violet",
        "com_tone_rose" to "Rose",
        "com_tone_amber" to "Amber",
        "com_tone_emerald" to "Emerald",
        "com_tone_slate" to "Slate",
        "com_language" to "Language",
        "login_title" to "Sign in",
        "login_subtitle" to "Use the login and password provided by admin or agent",
        "login_username" to "Username",
        "login_username_ph" to "e.g. client29072",
        "login_password" to "Password",
        "login_password_ph" to "Enter password",
        "login_button" to "Sign in",
        "login_hint" to "Get your credentials from your sales manager or admin panel",
        "login_invalid" to "Invalid username or password",
        "login_error" to "Connection error. Please try again",
        "login_client_only" to "This app is for clients only",
        "com_loading" to "Loading...",
    )

    fun t(lang: AppLanguage, key: String): String = when (lang) {
        AppLanguage.UZ -> uz[key]
        AppLanguage.UZ_KRIL -> uz_kril[key]
        AppLanguage.RU -> ru[key]
        AppLanguage.EN -> en[key]
    } ?: key
}
