import { defineConfig, type Plugin } from 'vite'
import path from 'path'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'

/** Build/dev da Firebase SW ni env dan yozadi */
function firebaseMessagingSwPlugin(): Plugin {
  const writeSw = () => {
    const apiKey = process.env.VITE_FIREBASE_API_KEY || 'REPLACE_WITH_FIREBASE_API_KEY'
    const authDomain = process.env.VITE_FIREBASE_AUTH_DOMAIN || 'REPLACE.firebaseapp.com'
    const projectId = process.env.VITE_FIREBASE_PROJECT_ID || 'REPLACE_WITH_YOUR_PROJECT_ID'
    const messagingSenderId = process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '000000000000'
    const appId = process.env.VITE_FIREBASE_APP_ID || '1:000000000000:web:0000000000000000000000'

    const source = `/* Auto-generated by vite — do not edit by hand */
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: ${JSON.stringify(apiKey)},
  authDomain: ${JSON.stringify(authDomain)},
  projectId: ${JSON.stringify(projectId)},
  messagingSenderId: ${JSON.stringify(messagingSenderId)},
  appId: ${JSON.stringify(appId)},
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = (payload.notification && payload.notification.title)
    || (payload.data && payload.data.title)
    || 'Lider Navoiy';
  const body = (payload.notification && payload.notification.body)
    || (payload.data && payload.data.body)
    || '';
  self.registration.showNotification(title, {
    body: body,
    icon: '/favicon.ico',
    data: payload.data || {},
  });
});
`
    const outDir = path.resolve(__dirname, 'public')
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true })
    fs.writeFileSync(path.join(outDir, 'firebase-messaging-sw.js'), source, 'utf8')
  }

  return {
    name: 'firebase-messaging-sw',
    buildStart() {
      writeSw()
    },
    configureServer() {
      writeSw()
    },
  }
}

function figmaAssetResolver() {
  return {
    name: 'figma-asset-resolver',
    resolveId(id) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.replace('figma:asset/', '')
        return path.resolve(__dirname, 'src/assets', filename)
      }
    },
  }
}

export default defineConfig({
  plugins: [
    figmaAssetResolver(),
    firebaseMessagingSwPlugin(),
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used – do not remove them
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory
      '@': path.resolve(__dirname, './src'),
    },
  },

  // File types to support raw imports. Never add .css, .tsx, or .ts files to this.
  assetsInclude: ['**/*.svg', '**/*.csv'],
})
